"""create admins table

Revision ID: 645b992c7c08
Revises: 
Create Date: 2026-06-30 13:40:15.236815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645b992c7c08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='账号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    
    from sqlalchemy.sql import text

    password_hash = "$2b$12$p5pBfwL/hwVsELYvTetAlufU2DGx3thPMJHX3EyAhyxxvD/vqFht6"
    init_sql = """
    INSERT INTO admins(username, password_hash, create_time, update_time)
    VALUES('admin', :password_hash, NOW(), NOW())
    """
    sql = text(init_sql)
    stmt = sql.bindparams(password_hash=password_hash)
    op.execute(stmt)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
