"""initial_migration

Revision ID: 7c07b7aedb5f
Revises: 
Create Date: 2026-07-01 17:26:39.737521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c07b7aedb5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='账号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    
    from sqlalchemy.sql import text

    password_hash = "$2b$12$p5pBfwL/hwVsELYvTetAlufU2DGx3thPMJHX3EyAhyxxvD/vqFht6"
    init_sql = """
    INSERT INTO admins(username, password_hash, create_time, update_time)
    VALUES('admin', :password_hash, NOW(), NOW())
    """
    sql = text(init_sql)
    stmt = sql.bindparams(password_hash=password_hash)
    op.execute(stmt)

    op.create_table('sql_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('query_id', sa.Integer(), nullable=False, comment='查询ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('query', sa.String(length=255), nullable=False, comment='查询sql'),
    sa.Column('query_ext1', sa.String(length=255), nullable=False, comment='扩展sql'),
    sa.Column('query_ext2', sa.String(length=255), nullable=False, comment='扩展sql2'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_version', 'sql_templates', ['query_id', 'version'], unique=False)
    op.create_table('view_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('view_id', sa.String(length=50), nullable=False, comment='视图唯一标识'),
    sa.Column('query_id', sa.Integer(), nullable=False, comment='查询ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='查询版本'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态：1-启用 0-禁用'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='视图描述'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_version', 'view_configs', ['query_id', 'version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_query_version', table_name='view_configs')
    op.drop_table('view_configs')
    op.drop_index('idx_query_version', table_name='sql_templates')
    op.drop_table('sql_templates')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
